name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Install elan
      run: |
          set -o pipefail
          curl -sSfL https://github.com/leanprover/elan/releases/download/v3.0.0/elan-x86_64-unknown-linux-gnu.tar.gz | tar xz
          ./elan-init -y --default-toolchain none
          echo "$HOME/.elan/bin" >> $GITHUB_PATH

    - name: Get z3 binary v4.11.2
      run: |
          set -o pipefail
          curl -OJLsSf https://github.com/Z3Prover/z3/releases/download/z3-4.11.2/z3-4.11.2-x64-glibc-2.31.zip
          unzip z3-4.11.2-x64-glibc-2.31.zip && rm z3-4.11.2-x64-glibc-2.31.zip
          echo "./z3-4.11.2-x64-glibc-2.31/bin/z3" >> $GITHUB_PATH

    - uses: actions/checkout@v3

    - name: Build LNSym
      run: make all
